-- Report upload flow in the app: the list of supported brokers comes from
-- here, and every uploaded report gets a row the app can poll while the
-- parser works on it.

-- Brokers whose reports the parser can read. id is the parser's broker
-- key (parser/cmd/main.go registers a parser per key) and is what the app
-- sends back as the "broker" form field on upload. A new broker = a parser
-- in the parser service + a row here.
CREATE TABLE IF NOT EXISTS brokers (
    id           TEXT PRIMARY KEY,
    name         TEXT NOT NULL,
    -- Accepted file extensions, lower case, without the dot.
    file_formats TEXT[] NOT NULL,
    -- Absolute URL or a path on gateway; NULL - the app draws a letter.
    icon_url     TEXT,
    color        TEXT, -- brand color "#RRGGBB"
    sort_order   INT NOT NULL DEFAULT 0,
    enabled      BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO brokers (id, name, file_formats, icon_url, color, sort_order)
VALUES ('sber', 'СберИнвестиции', ARRAY['html'], '/static/brokers/sber.png', '#21A038', 10)
ON CONFLICT (id) DO NOTHING;

-- One uploaded report on its way through the parser:
-- queued -> processing -> done | failed. id = task_id of the
-- report.uploaded message (generated by gateway).
CREATE TABLE IF NOT EXISTS report_imports (
    id                      UUID PRIMARY KEY,
    portfolio_id            UUID NOT NULL REFERENCES portfolios (id) ON DELETE CASCADE,
    broker_id               TEXT NOT NULL REFERENCES brokers (id),
    filename                TEXT NOT NULL DEFAULT '',
    status                  TEXT NOT NULL DEFAULT 'queued'
                                CHECK (status IN ('queued', 'processing', 'done', 'failed')),
    error                   TEXT NOT NULL DEFAULT '',
    trades_created          INT NOT NULL DEFAULT 0,
    trades_skipped          INT NOT NULL DEFAULT 0,
    cash_operations_created INT NOT NULL DEFAULT 0,
    cash_operations_skipped INT NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at             TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_report_imports_portfolio_id_created_at
    ON report_imports (portfolio_id, created_at DESC);
